# Generated by Django 3.1.1 on 2020-09-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_remove_movie_screen_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.person')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(related_name='played_in', through='movie_app.MoviePerson', to='movie_app.Person'),
        ),
    ]
