# Generated by Django 3.1.1 on 2020-09-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.producer'),
        ),
    ]
