# Generated by Django 3.1.1 on 2020-09-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_movie_producer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='Publisher',
        ),
    ]
